import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Scraping Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div class="container mx-auto px-6 py-2 flex justify-between items-center">
          <a class="font-bold text-2xl lg:text-4xl" href="#">
            Translate any CSV into a SQL Create Table Statement
          </a>
          <div class="block lg:hidden">
            <button class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-800 hover:border-teal-500 appearance-none focus:outline-none">
              <svg
                class="fill-current h-3 w-3"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <title>Menu</title>
                <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
              </svg>
            </button>
          </div>
          <div class="hidden lg:block">
            <ul class="inline-flex">
              <li>
                <a class="px-4 font-bold" href="/">
                  Home
                </a>
              </li>
              <li>
                <a class="px-4 hover:text-gray-800" href="#">
                  About
                </a>
              </li>
              <li>
                <a class="px-4 hover:text-gray-800" href="#">
                  Contact
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div
        class="py-20"
        style="background: linear-gradient(90deg, #667eea 0%, #764ba2 100%)"
      >
        <div class="container mx-auto px-6">
          <h2 class="text-4xl font-bold mb-2 text-white">
            Smart Health Monitoring Wristwatch!
          </h2>
          <h3 class="text-2xl mb-8 text-gray-200">
            Monitor your health vitals smartly anywhere you go.
          </h3>

          <button class="bg-white font-bold rounded-full py-4 px-8 shadow-lg uppercase tracking-wider">
            Pre Order
          </button>
        </div>
      </div>
    </div>
  );
}
